商品出品機能追加
testmpc/furima-38889 pull request #14
Opened 2023-06-04 09:05 UTC by testmpc

#What
・フリマアプリへ商品出品機能を追加
#Why
・追加した商品出品機能の妥当性の確認のため

2023-06-04 09:17 UTC, testmpc commented
下記にページの遷移等のgifやテストコードの成功画面を載せます。
・商品出品ページへ遷移成功
https://gyazo.com/62885c0f133e33a583a71f3ba1bb251f
・価格入力時に販売手数料と販売利益の表示成功
https://gyazo.com/885aa135ec5caa151463b9fb89ae3110
・商品出品成功
https://gyazo.com/d6397ffc4508cacda81e19a5cf119715
・商品出品失敗
https://gyazo.com/7e3a81bb5f3d19e31a06c870c3a99ad2
・商品出品ページへ遷移失敗
https://gyazo.com/ab9d429589e626ebc8da6c30677a7751
・テストコード成功
https://gyazo.com/ab9398fc56d16e56e21bb432b51b8a6f

2023-06-04 09:36 UTC, ShotaOtake reviewed
レビュー依頼を頂きありがとうございます！
追加で修正依頼のコメントをさせて頂きましたので、ご確認の上修正をお願い致します。

完成まであと一歩です！
引き続き実装頑張っていきましょう！

```
※テストコードにて修正箇所のございます際は、お手数ですが、最新の実行結果の画像も改めて添付頂きますようお願い致します。
```

2023-06-04 09:36 UTC, ShotaOtake commented on app/controllers/items_controller.rb
> +    @items = Item.all
◯下記の記述を修正していきましょう！
```
@items = Item.all
```

上記につきましては【一覧機能】の実装内容でございます。後ほど差分として上がるよう、現時点では削除、もしくはコメントアウトしておきましょう！

2023-06-04 09:36 UTC, ShotaOtake commented on app/javascript/item_price.js
> +    console.log(inputValue);
◎console.logの記述を削除しましょう！

```
開発完了後はデバッグ用の記述は不要であるため				
```

2023-06-04 09:36 UTC, ShotaOtake commented on app/javascript/item_price.js
> +window.addEventListener('load', () => {
◎メソッドを修正しましょう

小数点以下の除去処理についてはMath.floorメソッドが適当な実装です。

2023-06-04 09:36 UTC, ShotaOtake commented on app/models/item.rb
> +  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 },
◎バリデーションを修正しましょう！

```
validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 },
```

→現在の記述では小数の販売価格での登録が可能な状態となっているため。

2023-06-04 09:36 UTC, ShotaOtake commented on app/views/items/index.html.erb
>      <ul class='item-lists'>
◎修正内容をもとに戻しましょう

一覧表示機能の内容の実装が見受けられます。
該当機能実装時に差分として上げるために、現状は元の状態に戻しておきましょう！

2023-06-04 09:36 UTC, ShotaOtake commented on db/migrate/20230603114005_create_items.rb
> +    create_table :items do |t|
◎カラムにnull:falseを付与しましょう

NOTNULL制約のカラムを使用するため

2023-06-04 09:36 UTC, ShotaOtake commented on spec/models/item_spec.rb
> +
■テストの要件を追加しましょう！

現状、下記の要件が満たされていない状況でございます。

```
異常系
■ActiveHash５項目
・カテゴリーに「---」が選択されている場合は出品できない
・商品の状態に「---」が選択されている場合は出品できない
・配送料の負担に「---」が選択されている場合は出品できない
・発送元の地域に「---」が選択されている場合は出品できない
・発送までの日数に「---」が選択されている場合は出品できない
```

ActiveHashについては、空のステータスの代わりに「---」が選択されている場合のexampleが必要であるためです。

0、1などの数字を値に置く

2023-06-04 22:40 UTC, testmpc commented
・修正後のテストコードの成功画面。
https://gyazo.com/8f79f91b8122baf21f6498def26fc261

2023-06-05 05:00 UTC, sh10n7 requested changes
レビュー依頼ありがとうございます。
修正点確認させていただきました。

追加で修正いただきたい箇所をコメントさせていただきましたので、ご確認をお願いいたします。

また、修正後はコミットプッシュを確認いただき、再度**レビュー依頼フォーム**のご提出
をお願いいたします。

ご不明点や疑問点ございましたら、チャット・コネクトメンターにご相談ください！
よろしくお願いいたします。

2023-06-05 05:00 UTC, sh10n7 commented on app/models/item.rb
> +                    format: { with: /\A[0-9]+\z/, message: 'Please enter in half-width digit number' }
```
format: { with: /\A[0-9]+\z/, message: 'Please enter in half-width digit number' }
```
```/\A[0-9]+\z/```の正規表現は、integer型のカラムに対しては無効となります。
こちらの正規表現は削除しておきましょう。

2023-06-05 05:00 UTC, sh10n7 commented on app/views/items/index.html.erb
> +      <% if Item.exists? %>
```
<% if Item.exists? %>
```
こちらのif文は別機能の実装で記述する箇所になります。
実装前の段階のため、削除またはコメントアウトしておきましょう！

理由：
こちらのブランチで先の実装をおこなうと、今後正しくレビューできない可能性があるためです。

2023-06-05 14:55 UTC, testmpc commented
上記のご指摘を受けて商品出品機能追加修正２回を出したのでご確認よろしくお願いいたします。

2023-06-06 05:03 UTC, yuri240 reviewed
修正とレビュー依頼ありがとうございます。

しっかりと実装できていることが確認できましたので、
**LGTM**とさせていただきます！

また、以下に1点コメントを残させていただきましたので
確認の上でMergeしていただくようお願いいたします。

商品出品機能の実装、大変お疲れ様でした。
引き続き、応援しております。

2023-06-06 05:03 UTC, yuri240 commented on app/models/category.rb
> +    { id: 3, name: 'メンス' },
`{ id: 3, name: 'メンス' },`

`メンス`となっているため、`メンズ`に修正を行いましょう！

2023-06-06 21:55 UTC, merged